/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const isLocalhost = !!(window.location.hostname === "localhost");

const awsmobile = {
  aws_project_region: "ap-south-1",
  aws_cognito_region: "ap-south-1",
  aws_user_pools_id: "ap-south-1_5cELPF4U9",
  aws_user_pools_web_client_id: "5dmdli7mp80bj2pvc7leg8qk25",
  oauth: {},
  aws_cognito_username_attributes: ["email"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["email"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["Email"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["email"],
};

export default awsmobile;
